version: '3'

services:
  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    platform: linux/x86_64
    tty: true
    stdin_open: true
    build:
      context: .
    image: myapp
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
  bundle:
